[build]
  publish = "."        # your site root
  command = ""         # leave empty for static site

[functions]
  directory = "functions"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_SKIP_EXTENSIONS = "true"